### ISSUE TITLE
Exception in thread "Craft Scheduler Thread - 551" 

### ISSUE THREAD

**Issue by Dungjava** [Overwrite987/UltimateServerProtector#10]
I just got error after i joined server and keep spam
here is error : https://mclo.gs/oCHDyMK
Server version: 1.8.8 (FlamePaper)
Java 17
Plugin version 22.0
Full log server : https://mclo.gs/3rk054D

**Comment by Overwrite987** [comment]
I'm sorry for the long answer.
This error occurs frequently if you replace .the jar file of the plugin during its operation. 
If such an error occurs on the newest release, let me know.
