### ISSUE TITLE
При вводе пароля в консоли предупреждение

### ISSUE THREAD

**Issue by ICodeMonster** [Overwrite987/UltimateServerProtector#12]
логи - https://pastebin.com/eNUMMm1M
config.yml - https://pastebin.com/ceeWbnat
data.yml - https://pastebin.com/gUKJmKJ0

проблема появилась после перехода с прошлой версии на эту, если включить команду "pas", то будет жаловаться на неё.

**Comment by ICodeMonster** [comment]
вдобавок после перезагрузки - https://pastebin.com/kwZzw2bf
конфиг вроде цел, несколько раз проверял, настраивал с нуля - одно и тоже, не знаю в чём проблема

**Comment by ICodeMonster** [comment]
ошибка при вводе правильного пароля (с включённым /pas) = https://pastebin.com/HibFdkAb. Коммент выше ещё относится к присоединению на сервер

**Comment by Overwrite987** [comment]
Messages.yml
Отсутствует строка broadcasts.passed

**Comment by Overwrite987** [comment]
Как и все броадкасты в принципе

**Comment by ICodeMonster** [comment]
Странно, но все бродкасты присутствуют. Вот messages.yml - https://pastebin.com/HUZx8nLU

**Comment by Overwrite987** [comment]
Должно быть исправлено. Проблема заключалась в том, что сообщения не загружались если броадкасты отключены. Но они использовались в броадкастах для консоли
