### ISSUE TITLE
Плагин продолжает запрашивать пароль

### ISSUE THREAD

**Issue by ICodeMonster** [Overwrite987/UltimateServerProtector#13]
Если выдать игроку Н (из конфига) опку, а после её отобрать (игрок Н не вводит пароль), то плагин всё равно продолжает требовать пароль от игрока Н.

**Comment by Overwrite987** [comment]
> Если выдать игроку Н (из конфига) опку, а после её отобрать (игрок Н не вводит пароль), то плагин всё равно продолжает требовать пароль от игрока Н.

Это не так. 
После перезахода игрока его не будет спрашивать админ пароль.
Если он не хочет перезаходить - ну, будем честны, это уже его проблема.
