### ISSUE TITLE
I'm getting some errors, can you help me?

### ISSUE THREAD

**Issue by Boygamming1234** [Overwrite987/UltimateServerProtector#16]
My server version is 1.20.2, every time I enter the password it gives an error and asks me to re-enter it continuously. 
logs: https://pastes.dev/W63tN2mKU4

**Comment by Overwrite987** [comment]
> My server version is 1.20.2, every time I enter the password it gives an error and asks me to re-enter it continuously. logs: https://pastes.dev/W63tN2mKU4

please send full log
