### ISSUE TITLE
Suggestion :

### ISSUE THREAD

**Issue by TANJIL87** [Overwrite987/UltimateServerProtector#18]
Please add MySQL support or the data. So we can connect the database from different server. So if I login in the lobby, I won't have to login on the other backend server where I'm using USP . Or maybe bungeecord/velocity support :) . Really appreciate your work <3 .

**Comment by Overwrite987** [comment]
> Please add MySQL support or the data. So we can connect the database from different server. So if I login in the lobby, I won't have to login on the other backend server where I'm using USP . Or maybe bungeecord/velocity support :) . Really appreciate your work <3 .

make fun
https://disk.yandex.ru/d/rEpc-thYCoFIeQ
