### ISSUE TITLE
Password entry bug

### ISSUE THREAD

**Issue by zKOSMOSz** [Overwrite987/UltimateServerProtector#22]
When I enter the password, it says what is correct. But immediately after that, he writes an error.
---
Когда я ввожу пароль, он сообщает, что является правильным. Но сразу после этого он пишет ошибку.

![image](https://github.com/Overwrite987/UltimateServerProtector/assets/115968653/230eced4-3eda-452e-9251-164bc84308ff)
![image](https://github.com/Overwrite987/UltimateServerProtector/assets/115968653/d4cbdc63-f2cf-43d9-bf5f-3cc19c733619)

I'm sorry if I didn't create it there, I don't use github.
---
Извините если не там создал, не пользуюсь github.

**Comment by Overwrite987** [comment]
> ## When I enter the password, it says what is correct. But immediately after that, he writes an error.
> Когда я ввожу пароль, он сообщает, что является правильным. Но сразу после этого он пишет ошибку.
> 
> ![image](https://private-user-images.githubusercontent.com/115968653/301213197-230eced4-3eda-452e-9251-164bc84308ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MzczMzUsIm5iZiI6MTcwNjczNzAzNSwicGF0aCI6Ii8xMTU5Njg2NTMvMzAxMjEzMTk3LTIzMGVjZWQ0LTNlZGEtNDUyZS05MjUxLTE2NGJjODQzMDhmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQyMTM3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTY0ZDIwZDk2ZTMzZDVkNTUyOTIyNjljODMwNWUzZmUyYjY4MzhlMWZjYjJlYWFjY2FmMDE5NWMxMmZiZTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GVhEPLmQInFABsIsQVAkgnLBiRqQ6pI73LV6tQ8GIwI) ![image](https://private-user-images.githubusercontent.com/115968653/301213450-d4cbdc63-f2cf-43d9-bf5f-3cc19c733619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MzczMzUsIm5iZiI6MTcwNjczNzAzNSwicGF0aCI6Ii8xMTU5Njg2NTMvMzAxMjEzNDUwLWQ0Y2JkYzYzLWYyY2YtNDNkOS1iZjVmLTNjYzE5YzczMzYxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQyMTM3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjYyOGI3ZTRmNGFiNjE4OWMxYzczMjU1NzI1Mjk1YWM3YmYxMTE1Mjg2N2E5YjkzNTZlYjk0ZGZmMjE0ODJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yuc8tayqk5y-Vfm1FRJU_2hfhxGrWqZS1R7l_bVc8Js)
> 
> ## I'm sorry if I didn't create it there, I don't use github.
> Извините если не там создал, не пользуюсь github.


problem is in messages.yml, so just upgrade it to latest
