### ISSUE TITLE
Request 1.8 support ! 

### ISSUE THREAD

**Issue by TANJIL87** [Overwrite987/UltimateServerProtector#27]
Is it possible to add support for 1.8 , maybe with less stuff than original one for compatibility ! bcz so many servers still uses 1.8 , specially for pvp type gamemodes ! Since USP isn't available for bungeecord/velocity !

**Comment by Overwrite987** [comment]
> Is it possible to add support for 1.8 , maybe with less stuff than original one for compatibility ! bcz so many servers still uses 1.8 , specially for pvp type gamemodes ! Since USP isn't available for bungeecord/velocity !

It works fine for me
![image](https://github.com/Overwrite987/UltimateServerProtector/assets/92237090/a8aabb61-e0e1-4b63-a23f-a7a198a920ec)

**Comment by TANJIL87** [comment]
Umm so I guess it's problem only for me ..
Getting this error in 1.8

https://mclo.gs/OA6vq2P

**Comment by Overwrite987** [comment]
> Author

can you just download latest version...
