### ISSUE TITLE
 Normal members who are not on the op list will still be kicked for not entering a password

### ISSUE THREAD

**Issue by hiiamken** [Overwrite987/UltimateServerProtector#33]
The member on my server is having an error, even though it's not a staff member, but it's still kicked
![image](https://github.com/Overwrite987/UltimateServerProtector/assets/142149960/758fee9b-7ddc-411a-8791-8d046b150ef7)
![image](https://github.com/Overwrite987/UltimateServerProtector/assets/142149960/e5627e36-d290-48df-bb75-a3bddf02d01e)
![image](https://github.com/Overwrite987/UltimateServerProtector/assets/142149960/f9d4fba4-f622-432d-8fd7-7ee7e240613d)
![image](https://github.com/Overwrite987/UltimateServerProtector/assets/142149960/e08296c2-b615-4464-ac0f-a1c3c47c9492)

**Comment by Overwrite987** [comment]
Are you sure you have the correct version of the plugin installed?
Where did you download it from?

**Comment by hiiamken** [comment]
> Are you sure you have the correct version of the plugin i
<img width="338" alt="Ảnh màn hình 2024-04-12 lúc 19 53 40" src="https://github.com/Overwrite987/UltimateServerProtector/assets/142149960/211195e5-8b87-489e-bcbf-ac00b65aac47">
nstalled? Where did you download it from?

I only use spigot

**Comment by hiiamken** [comment]
He's been playing normally for the past few days, but suddenly when he joined, he got the same error. I use usp for other servers and he joins those servers normally

**Comment by Overwrite987** [comment]
Unable to reproduce. 
If this will happen again - reopen this issue, but i think it is most likely some specific bug
