### ISSUE TITLE
Add an api method for full login

### ISSUE THREAD

**Issue by masmc05** [Overwrite987/UltimateServerProtector#34]
Currently the full logic is only here <https://github.com/Overwrite987/UltimateServerProtector/blob/94e9bff8f9d7c80bc12667fea218a2346a4e4d3f/bukkit/src/main/java/ru/overwrite/protect/bukkit/PasswordHandler.java#L112-L173>

It would be good if we could use all the login logic without just copy pasting it, so it could contain all the future changes.

Current purpose: Alternative custom login addon for test proxies with lots of servers without players (so no plugin messages)

**Comment by Overwrite987** [comment]
Now this method is public so you can use it
