### ISSUE TITLE
Problem with Citizens npc command .

### ISSUE THREAD

**Issue by TANJIL87** [Overwrite987/UltimateServerProtector#37]
So it's been a problem since the beginning but It's probably is a function of this plugin . 

So if I set command to run as op in the Citizens NPC and any player uses that NPC, they're flagged as op, and they need to enter the admin password even though they don't have op. 

For example , I have a npc and added command "/npc cmd add dmenu open levels -p -o" 

So, Is it possible to add compatibility with citizens ? So if anyone runs the command from the npc they won't get flagged.

**Comment by Overwrite987** [comment]
> So it's been a problem since the beginning but It's probably is a function of this plugin .
> 
> So if I set command to run as op in the Citizens NPC and any player uses that NPC, they're flagged as op, and they need to enter the admin password even though they don't have op.
> 
> For example , I have a npc and added command "/npc cmd add dmenu open levels -p -o"
> 
> So, Is it possible to add compatibility with citizens ? So if anyone runs the command from the npc they won't get flagged.

Can you install latest dev build from actions and show logs if this keeps happening?

**Comment by TANJIL87** [comment]
Here
https://mclo.gs/93J9gZC

**Comment by Overwrite987** [comment]
> Here https://mclo.gs/93J9gZC

This is the most dumb stuff I have EVER seen in my life. 
Explanation:
Here you can see: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/util/Util.java that Citisens ACTUALY GIVES PLAYER OP to force player execute command.

And this is incredibly dumb for one reason - a player can have time to execute ANY command in that time...

And i recommend you DELETE CITIZENS RIGHT NOW... This looks lika a HUGE vulnerability...
