### ISSUE TITLE
Velocity Compatibility ? 

### ISSUE THREAD

**Issue by NemesiusPat06** [Overwrite987/UltimateServerProtector#39]
Hello, I want to use your plugin with velocity but I see the plugin is only compatible with Bungee&Bukkit server
It is on your to do list ?

**Comment by Overwrite987** [comment]
> Hello, I want to use your plugin with velocity but I see the plugin is only compatible with Bungee&Bukkit server It is on your to do list ?

Well, plugin actually ain't compatible with ANY proxy in the sense that you can't install it on any proxy server.

If you mean proxy: true - it only sends messages across your network via bungee plugin messaging channel, that velocity also has.
