### ISSUE TITLE
Предложение/вопрос

### ISSUE THREAD

**Issue by euj3ne** [Overwrite987/UltimateServerProtector#8]
Приветствую! А когда добавите поддержку БД mysql или postgresql?

**Comment by Overwrite987** [comment]
> Приветствую! А когда добавите поддержку БД mysql или postgresql?

У плагина есть своё апи, что позволяет написать аддон для поддержки MySql.
У меня его уже заказал один человек и он уже готов и работает, но в открытый доступ я его выставлять не хочу.

**Comment by Overwrite987** [comment]
Объективно не issue
