### ISSUE TITLE
Не работает функция отключения сессии 

### ISSUE THREAD

**Issue by StKillReal** [Overwrite987/UltimateServerProtector#9]
Нужно чтобы при входе админа его всегда просило пароль, даже в случае смены ip адреса, но при выключении функции сессий, плагин все равно ждет смены ip для запроса пароля.

**Comment by Overwrite987** [comment]
> Нужно чтобы при входе админа его всегда просило пароль, даже в случае смены ip адреса, но при выключении функции сессий, плагин все равно ждет смены ip для запроса пароля.

Можешь предоставить свой файл конфигурации? Буду тестировать

**Comment by StKillReal** [comment]
> > Нужно чтобы при входе админа его всегда просило пароль, даже в случае смены ip адреса, но при выключении функции сессий, плагин все равно ждет смены ip для запроса пароля.
> 
> Можешь предоставить свой файл конфигурации? Буду тестировать
[config.zip](https://github.com/Overwrite987/UltimateServerProtector/files/12193886/config.zip)

**Comment by Overwrite987** [comment]
Должно быть исправлено в дев билде.
Можешь скачать его [из Actions](https://github.com/Overwrite987/UltimateServerProtector/actions)

> > > Нужно чтобы при входе админа его всегда просило пароль, даже в случае смены ip адреса, но при выключении функции сессий, плагин все равно ждет смены ip для запроса пароля.
> > 
> > 
> > Можешь предоставить свой файл конфигурации? Буду тестировать
> > [config.zip](https://github.com/Overwrite987/UltimateServerProtector/files/12193886/config.zip)
